//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Itsg.Ostc2
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName = "OSTCListe")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName = "OSTCListe")]
    public partial class OstcListe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OstcListeListe listeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OstcListeListe Liste {
            get {
                return this.listeField;
            }
            set {
                this.listeField = value;
                this.RaisePropertyChanged("Liste");
            }
        }

        /// <remarks/>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        /// <remarks/>
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum OstcListeListe {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("annahme-pkcs.agv")]
        annahmepkcsagv,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("annahme-pkcs.key")]
        annahmepkcskey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("annahme-sha256.agv")]
        annahmesha256agv,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("annahme-sha256.key")]
        annahmesha256key,
    }
}
